### ISSUE TITLE
Investigate modifying .js demo files script to add comment to demo .js files

### ISSUE THREAD

**Issue by arnavic** [allenai/varnish-mui#11]
With the latest material ui update getting merged into varnish-mui, we can no longer have only .tsx demo components in the docs; we need to run a comand "yarn docs:typescript:formatted" to produce .js versions of the TS demo components to reference in the demo .md files. 
Given this, let's investigate modifying the script that runs upon executing yarn docs:typescript:formatted to see if we can add a note to all .js files in the docs to call this behavior out and avoid confusion.

**Comment by jonborchardt** [comment]
done
