### ISSUE TITLE
Select label doesn't display properly

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-mui#113]
The label text for a select is hard to read:

<img width="283" alt="Screenshot 2023-05-01 at 9 44 04 PM" src="https://user-images.githubusercontent.com/801451/235581097-7eb5eb1f-a436-4f55-8acc-1301516ebc2e.png">

Notice how the input border isn't hidden like it is for text inputs:

<img width="1423" alt="Screenshot 2023-05-01 at 9 45 11 PM" src="https://user-images.githubusercontent.com/801451/235581235-caff5ea8-063c-4b2c-aaf2-5f700c37d323.png">

**Comment by jonborchardt** [comment]
@codeviking did you find an acceptable resolution, or do you still think there needs to be a varnish fix?

**Comment by codeviking** [comment]
I stopped using a select.

I'm unclear why it works in the template but didn't in my example. It seems like a bug in Varnish, so I suspect someone should dig in to try to come up with a repro + fix.

That said it clearly works in the template, which means the "bug" could've been an artifact of my usage. I'm fine if it gets closed if it's not something we can easily reproduce.

**Comment by jonborchardt** [comment]
coolio, ill dig in, TY

**Comment by arnavic** [comment]
@codeviking -- do you have more code that you could provide re: the example where this wasn't working? i've tried it in the Varnish docs and in different places in the basic skiff template demo and I'm unable to get a repro... but if you have a branch or more specific code pointers that you could send my way to try and get the same repro I'm happy to investigate that! I just am unsure how to recreate the bug right now on my end.

**Comment by codeviking** [comment]
I've since refactoring things; the code is considerably different at this point. I could rewind history to reproduce things, but it's probably not worth it. I suspect this was a side-effect of how I had assembled things at that time, and isn't worth worrying about it.

I think we can close this. If we see another instance we can reopen the ticket and dive in then. Thanks for taking a look!
