### ISSUE TITLE
Unclear how to use spacing values

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-mui#114]
I went [here](https://varnish.allenai.org/material-ui/varnish/varnish-theme/) looking for how to reference `spacing` values.

I expanded the "spacing" item, but nothing is there:

<img width="846" alt="Screenshot 2023-05-01 at 9 46 15 PM" src="https://user-images.githubusercontent.com/801451/235581348-8174177c-1205-45ff-ab91-cf721d4c6813.png">

**Comment by arnavic** [comment]
we're using MUI's spacing guidelines - https://mui.com/material-ui/customization/spacing/
let's make sure it's more apparent from our Varnish docs

**Comment by arnavic** [comment]
done
