### ISSUE TITLE
Add a page for all varnish1 systems that were removed... and point to the mui way

### ISSUE THREAD

**Issue by jonborchardt** [allenai/varnish-mui#117]
https://varnish-deprecated.apps.allenai.org/components/breakpoints
https://varnish-deprecated.apps.allenai.org/components/link_css
https://varnish-deprecated.apps.allenai.org/components/shadows
https://varnish-deprecated.apps.allenai.org/components/shape
https://varnish-deprecated.apps.allenai.org/components/spacing
https://varnish-deprecated.apps.allenai.org/components/table_extensions
https://varnish-deprecated.apps.allenai.org/components/text_styles
https://varnish-deprecated.apps.allenai.org/components/transitions

**Comment by arnavic** [comment]
done
