### ISSUE TITLE
Add Link Theming Override + Change Footer Link to Respect Accordingly

### ISSUE THREAD

**Issue by arnavic** [allenai/varnish-mui#12]
Add Link Theming Override + Change Footer Link to Respect Accordingly

**Comment by jonborchardt** [comment]
this is poorly defined and needs some investigation
i think we should add styles to the varnish theme and be able to export that style for use in varnish-react-router AND use them in the varnish theme that is rolled into the material theme.
original code: https://github.com/allenai/varnish/blob/main/packages/varnish/components/LinkCSS.tsx

**Comment by arnavic** [comment]
closed with #9 and #41 

React-Router work will be rolled into the react-router PR and issue
