### ISSUE TITLE
Consider switching away from yarn

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-mui#143]
Apparently `yarn` < 2 is EoL:
https://classic.yarnpkg.com/lang/en/docs/install/#mac-stable

That's what we're using, as yarn 2 made several breaking changes we didn't want to adopt.

We should consider using `npm` again, as my understanding is it's now better (they caught up).

When we do this, we should update the various templates.

**Comment by jonborchardt** [comment]
doubling down using yarn workspaces
