### ISSUE TITLE
Get rid of right padding on header nav

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/varnish-mui#147]
The default header nav has unnecessary padding on the right. Visually, it's causing there to be significantly more whitespace in the top right corner than in the top left.

![image](https://github.com/allenai/varnish-mui/assets/8367927/509d520e-43d6-45cf-a14a-df08c5061e34)

**Comment by arnavic** [comment]
this actually already happens -- the MenuColumns item in Varnish is just a div which has 0 padding by default. It's just that the Dolma code does not properly use the MenuColumns item. Closing this and will open a ticket on Dolma (ands skiff-template) for the corresponding fixes to show best practice here.
