### ISSUE TITLE
module augmentation does not appear to be working

### ISSUE THREAD

**Issue by jonborchardt** [allenai/varnish-mui#159]
module augmentation does not appear to be passing from packages to app. 
this is why i added  @types/mui.d.ts to varnish-demo. we need to either (a is WAY better):
 * a- make work and ensure that users like the skiff template don't need to add a @types/mui.d.ts file (and remove it from varnish-demo)
 * b- or, add docs on how to add the type file to varnish apps, (and add it to skiff-template for the user)

**Comment by ericmarsh995** [comment]
Resolved by https://github.com/allenai/varnish/pull/588
