### ISSUE TITLE
Add new package varnish-eslint-config to varnish-mui in the packages folder

### ISSUE THREAD

**Issue by jonborchardt** [allenai/varnish-mui#16]
original code: https://github.com/allenai/varnish/tree/main/packages/eslint-config-varnish
original docs: none, but please add new docs anyway

this will be deployed to npm as a different lib than varnish (add a new folder here: https://github.com/allenai/varnish-mui/tree/main/packages)
this ticket does NOT include npm work
just get the code working in the new demo (note, it wont be used by other packages in varnish-mui, because we are using the styling of mui for now)

**Comment by arnavic** [comment]
closed with #42
