### ISSUE TITLE
build is broken

### ISSUE THREAD

**Issue by jonborchardt** [allenai/varnish-mui#164]
prod deploy of varnish-demo fails to build on skiff, figure out why and resolve
local docker build is not working for arnavic, figure out why and resolve

**Comment by arnavic** [comment]
this is done.

**Comment by jonborchardt** [comment]
what fixed the prod/adhoc build?

**Comment by arnavic** [comment]
> what fixed the prod/adhoc build?

https://github.com/allenai/varnish/pull/572#discussion_r1439788180
