### ISSUE TITLE
investigate tsup

### ISSUE THREAD

**Issue by mtblanton** [allenai/varnish-mui#173]
Look into implementing [tsup](https://github.com/egoist/tsup) for our build. 

Evaluate if it streamlines our build process, changes package size, and keeps the same functionality. 

Things to check:
[ ] Types are usable in dependent projects
[ ] Package is usable in CJS and ESM projects
[ ] Package size doesn't go up a ton
[ ] Package is tree-shakeable (if it already is)

**Comment by jonborchardt** [comment]
done
