### ISSUE TITLE
add a typography page to demo

### ISSUE THREAD

**Issue by jonborchardt** [allenai/varnish-mui#175]
we should show examples of how to use each of the typography (mimic what we have in mui docs)
i want this here because it is super commonly used, and going to mui is slightly harder

something like this: https://github.com/allenai/varnish/blob/aee946484e681c1f2286b92533dcbfc9bf8ca875/apps/varnish-demo/src/pages/TextStyles/page.mdx#L22

but demos using the correct typography from mui

**Comment by ericmarsh995** [comment]
Closed by https://github.com/allenai/varnish/pull/591
