### ISSUE TITLE
Investigate if we need to bring over any additional styles for text

### ISSUE THREAD

**Issue by jonborchardt** [allenai/varnish-mui#19]
I believe we do not, but here is the code in case design wants to.
original code: https://github.com/allenai/varnish/blob/main/packages/varnish/components/textStyles.tsx
original demo: https://github.com/allenai/varnish/tree/main/apps/varnish-demo/src/pages/TextStyles

if we alter these, we should inspect the existing demo code to make sure it still looks good, and consider adding additional demo for any new styles we added

**Comment by jonborchardt** [comment]
from design: (note, im not sure we should do this yet)
Note: Figma doesn't understand REM, so it's in pixels. Additionally, the 400 weight of Lato in this case refers to Regular, and the 700 weight refers to Bold. I don't know why Figma has different weights. I don't lose sleep over it.

//styleName: typography/h1;
font-family: Lato;
font-size: 46px;
font-weight: 700;
line-height: 63px;

//styleName: typography/h2;
font-family: Lato;
font-size: 36px;
font-weight: 700;
line-height: 49px;

//styleName: typography/h3;
font-family: Lato;
font-size: 30px;
font-weight: 700;
line-height: 41px;

//styleName: typography/h4;
font-family: Lato;
font-size: 24px;
font-weight: 700;
line-height: 33px;

//styleName: typography/h5;
font-family: Lato;
font-size: 20px;
font-weight: 400;
line-height: 27px;

//styleName: typography/h6;
font-family: Lato;
font-size: 14px;
font-weight: 400;
line-height: 19px;
letter-spacing: 1px;   

//styleName: typography/body;
font-family: Lato;
font-size: 16px;
font-weight: 400;
line-height: 22px;

//styleName: typography/body2;
font-family: Lato;
font-size: 16px;
font-weight: 700;
line-height: 22px;

//styleName: typography/subtitle1;
font-family: Lato;
font-size: 14px;
font-weight: 400;
line-height: 19px;

//styleName: typography/subtitle2;
font-family: Lato;
font-size: 14px;
font-weight: 700;
line-height: 19px;

//styleName: typography/overline;
font-family: Lato;
font-size: 12px;
font-weight: 400;
line-height: 24px;
letter-spacing: 1px;

//styleName: typography/caption;
font-family: Volkhov;
font-size: 22px;
font-weight: 400;
line-height: 37px;

**Comment by jonborchardt** [comment]
@samstuesser can you please look at: https://varnish-mui.apps.allenai.org/material-ui/react-typography/
and let me know what we need to change

(not to be parity with old varnish.. but change for the best future)

**Comment by samstuesser** [comment]
> (note, im not sure we should do this yet)

Yes, as a starting point, the core type styles above need to be implemented **before** I can take a look at the WIP environment

Exception to this-- Volkov, that should be a custom style (it doesn't fit well for that token)

**Comment by samstuesser** [comment]
<img width="1034" alt="Screen Shot 2023-02-16 at 4 09 20 PM" src="https://user-images.githubusercontent.com/84743347/219516174-e1e74197-b104-42bc-a18e-b8d041d85204.png">
Here's a good example as to why. The default weight here is much thinner than Lato Bold

**Comment by jonborchardt** [comment]
hmm.... how did you get that?
i see:
![image](https://user-images.githubusercontent.com/8194065/219516665-b1ae2fdc-c4f5-4f85-be04-59d85d556a85.png)

**Comment by samstuesser** [comment]
I took a screenshot. Either way, the weight in your screenshot is still incorrect.

**Comment by jonborchardt** [comment]
i have no idea why you are seeing such a small font weight.. maybe hard refresh?

anyhow...

yes, the above is stock material with lato..
if you want it, ill make the changes in this ticket.. but i thought you wanted to look at it in lato before making that call.

**Comment by samstuesser** [comment]
Yes, I was able to make our Ant.D work directly in MUI, and then I exported those styles for you so we could see them. That's the rationale behind sending that information over, and doing that conversion work on my end.

As I said, I haven't finished what components will inherit which of these tokens, but yes it would be great! Thank you.

**Comment by samstuesser** [comment]
Hmm, I looked into this more and it looks like a Chrome issue.

I cleared the cookies and cache in both Chrome and Safari for Mac. Safari renders it how you see it (the 400 weight semibold) but Chrome is sticking with the super thin weight for some reason:
<img width="967" alt="Screen Shot 2023-02-16 at 4 25 19 PM" src="https://user-images.githubusercontent.com/84743347/219518788-9c5be426-f05b-44aa-8d7e-863d4d7f095b.png">
<img width="909" alt="Screen Shot 2023-02-16 at 4 25 32 PM" src="https://user-images.githubusercontent.com/84743347/219518791-4c7564f8-7804-4f38-b856-c9dc9922d245.png">

**Comment by samstuesser** [comment]
Hello, the [typography style guide is available on this page in Figma](https://www.figma.com/file/11UobOSIbxrl0zxHgbpjWU/%2FWIP%2F-Varnish-2.0?node-id=21%3A69603), with interactive examples to the side.

Here's the whole thing exported as a JPG.
![Varnish2_Complete Typography](https://user-images.githubusercontent.com/84743347/221686622-8c63559f-5633-4d3b-8799-166d51313b73.jpg)




**Next steps for me:** Now that you have all the typographic and color styles you need, I can look for any component or element-level deviations from MUI default. I would anticipate not very many of these, but I can break them up per component type. **The base theme, particularly color and typography, is good to implement immediately.**

**Comment by jonborchardt** [comment]
the work for the main theme is complete and building on prod.
additional theming of component text styles will be done later as separate issues.
