### ISSUE TITLE
Add a material design version of the AI2 footer to this project

### ISSUE THREAD

**Issue by jonborchardt** [allenai/varnish-mui#5]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

we are converting from antd to material
this ticket is to convert the footer component

current footer is here: https://github.com/allenai/varnish/tree/main/packages/varnish/components
docs: https://github.com/allenai/varnish/tree/main/apps/varnish-demo/src/pages/Footer

the code will be added to: https://github.com/allenai/varnish-mui/tree/main/packages/varnish/src
docs added here: https://github.com/allenai/varnish-mui/tree/main/docs/pages/material-ui/varnish

this project is just starting, so there are likely loose ends that need to be thought through when we hit them.... ping me when needed!

**Comment by arnavic** [comment]
closed with ai2-footer PR merge
