### ISSUE TITLE
Disabled primary button does not look good

### ISSUE THREAD

**Issue by jonborchardt** [allenai/varnish-mui#55]
![image](https://user-images.githubusercontent.com/8194065/225766748-903d30e0-9cc5-4507-a2ba-9c6f2d63c038.png)

- [ ] i think we need white text at the very least
- [ ] also test other variants to make sure they all look good

**Comment by arnavic** [comment]
i'm using the disabled button colors from this part of the Figma file as a guidance for this - https://www.figma.com/file/11UobOSIbxrl0zxHgbpjWU/%5E_%5E--*~*~*WIP*~*~*-Varnish-2.0-Component-Library?node-id=10120-139408&t=t5dwM9eFWWBMuDrl-4

**Comment by jonborchardt** [comment]
the issue may be that the theme override file may need to specify palette->action->*Opacity values as seen here: https://varnish-mui.apps.allenai.org/material-ui/customization/default-theme/

**Comment by jonborchardt** [comment]
fixed and validated on skiff-template
