### ISSUE TITLE
Make it so pull requests dont go to MUI/master by default and instead to varnish-mui/main

### ISSUE THREAD

**Issue by jonborchardt** [allenai/varnish-mui#67]

**Comment by arnavic** [comment]
@jonborchardt it looks like this is currently unsupported by GitHub, and they are investigating allowing this -- https://github.com/orgs/community/discussions/11729 

Checkout out various online instructions about this and they all seem to point to the same thing which is that currently this behavior can't be modified for forked repos. 
Should we leave this issue open or close it for now?

**Comment by jonborchardt** [comment]
Bummer, save for later.

**Comment by arnavic** [comment]
added a wontfix label since we can't change this right now, unassigning myself as well. this can be picked up at a future time when there is support from GitHub.

**Comment by jonborchardt** [comment]
will be moot as we drop the fork
