### ISSUE TITLE
Are the headings supposed to be blue?

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-mui#79]
The headings on the new Skiff template are blue:

<img width="976" alt="Screenshot 2023-03-22 at 10 21 26 PM" src="https://user-images.githubusercontent.com/801451/227110843-0ad2dca8-1c9e-4017-94d2-d2b54721002c.png">

The prior headings were black / gray:

<img width="976" alt="Screenshot 2023-03-22 at 10 21 33 PM" src="https://user-images.githubusercontent.com/801451/227110860-3af46fdf-ef20-446f-8783-a5bac75b3e81.png">

I prefer the former. The blue variety look like links to me.

**Comment by codeviking** [comment]
Gotcha.

I think was actually the reverse. Skiff Template came first, and I suspect most of our demos use that treatment (as that's the codebase they start from). The website was a derivation.

That said I don't think we need to worry too much about past precedent. We should just make a call as to what we think is preferable, and slowly make our way towards that being consistent.

@samstuesser which variant do you prefer / think should be the default, sans any consideration of current defaults? If we like the blue headings I'm totally ok with that, I just noticed the difference!

**Comment by samstuesser** [comment]
Sure, I am just giving the limited information I have due to the lack of historical documentation. B6 uniform would be great

**Comment by jonborchardt** [comment]
just throwing out an option

one option i to have the MUI typography headings of type primary be b3 ... and the h1...h6 be n5
so
<Typography level="h1"> <- blue
<h1> <- black

thoughts?

**Comment by samstuesser** [comment]
I understand, just giving context with what I have to work with

**Comment by jonborchardt** [comment]
i am not entirely sure what to do.
im going to leave them blue unless otherwise directed.

**Comment by samstuesser** [comment]
@jonborchardt consolidated feedback https://github.com/allenai/varnish-mui/issues/81, since there were 2 issues about the header

**Comment by jonborchardt** [comment]
@samstuesser 
yes, i made the header n5.
the question from sam is, should all h1-h4's on all demos and on ai2-web be blue? (https://varnish-mui.apps.allenai.org/material-ui/react-typography/)
and i believe your answer is yes.

**Comment by samstuesser** [comment]
Based on frequency (a single instance of N5 within a preexisting pattern) versus many instances of the B3(formerly B6) headlines, I'd vote for B6 as the default, and considering this a custom pattern

**Comment by samstuesser** [comment]
Ah, it's hard to determine what the question is!

yes, headlines should be blue. The headER unit is the custom pattern, which uses N5

**Comment by jonborchardt** [comment]
Ok. So closing this issue. Ty
