### ISSUE TITLE
The header is bigger on the new template.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-mui#81]
This might be intentional, but I noticed that the header on the new template is a bit bigger:

<img width="1474" alt="Screenshot 2023-03-22 at 10 24 22 PM" src="https://user-images.githubusercontent.com/801451/227111296-2d435ccd-3d23-4116-91af-188af364d7a7.png">

I have a slight preference for the tighter spacing, as it means the header takes up less space (so there's more for the content, which is probably more interesting!).

**Comment by samstuesser** [comment]
H1 size has not changed between Varnish 1.0 and Varnish 2.0

If you're noticing a change, it means Skiff was originally off from ai2-web

**Comment by codeviking** [comment]
@samstuesser this isn't about the headings (the h1), it's about the `<header />` at the top of the page.

It looks like there's more white space between the logo and the `<header />`'s boundaries.

**Comment by samstuesser** [comment]
I couldn't tell you without inspecting it. This isn't derived from Design.

If I had to guess, the height of the container is still determined by logo height, which would mean it varies. I'd love to make it uniform.

**Comment by codeviking** [comment]
>  I'd love to make it uniform.

Is the existing height (what's in Skiff template now) the one you prefer?

FYI @jonborchardt @arnavic. It looks like extra height might be attributable to the menu in the top-right:

<img width="318" alt="Screenshot 2023-03-23 at 9 04 35 AM" src="https://user-images.githubusercontent.com/801451/227264013-f741be4b-a856-4856-b4c0-cfba71d25d31.png">

If I toggle this CSS off, things look better:

```css
.css-i6s8oy {
    min-height: 64px;
}
```

Also, it looks like these heights are dictated by the screen size, as there's multiple being applied:

<img width="354" alt="Screenshot 2023-03-23 at 9 06 12 AM" src="https://user-images.githubusercontent.com/801451/227264486-3d9c0c49-0c37-4212-9e2a-3d2363ac92da.png">

I wonder if there's something in the theme that dictates these values?

**Comment by jonborchardt** [comment]
@samstuesser @codeviking 
OOPS, this is my bad, ill fix

**Comment by samstuesser** [comment]
@jonborchardt @codeviking idk if this is accurate or not, but I'm wondering if the difference between `min height` above is with/without the hamburger menu on mobile? It appears that the breakpoint is 600px in width

I could be way wrong

**Comment by jonborchardt** [comment]
the height difference has to do with the menu (which i am fixing soon)
the width issue has to do with a missing context (which i am fixing soon)

**Comment by jonborchardt** [comment]
i replaced the links with a menu and fixed the header height
building on prod now
