### ISSUE TITLE
Headings should (probably) have more space above than below.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-mui#82]
On the new template, it looks like the space above and below headings is the same:

<img width="1037" alt="Screenshot 2023-03-22 at 10 26 05 PM" src="https://user-images.githubusercontent.com/801451/227111597-6305acef-2ff4-4342-8a02-19908e2d807b.png">

See what this looks like on the old/current template:

<img width="1037" alt="Screenshot 2023-03-22 at 10 27 12 PM" src="https://user-images.githubusercontent.com/801451/227111741-61ed4383-a7b5-4ab8-9036-8acf351caa50.png">

I prefer the original treatment, as it makes it clear what text the heading is affiliated with (the text that's closer to). I think this makes things easier to scan.

**Comment by jonborchardt** [comment]
this should now be resolved (building template now)
