### ISSUE TITLE
Large blocks of text should have a max width.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-mui#83]
The text on the about page spans the entire width of the main content:

<img width="1690" alt="Screenshot 2023-03-22 at 10 28 47 PM" src="https://user-images.githubusercontent.com/801451/227111952-ced02427-e979-4dad-9a49-6f0d95dc1718.png">

I think the text is a lot easier if there's a max width set (in this case I used `70ch`):

<img width="1690" alt="Screenshot 2023-03-22 at 10 30 13 PM" src="https://user-images.githubusercontent.com/801451/227112153-1dc81ab3-5379-4c03-a79d-a1ceac3554d0.png">

There's a good explanation for why here:
https://baymard.com/blog/line-length-readability

Admittedly we didn't do this before, so this isn't a bug. But I think it'd be a nice feature to have (and I think we had a component for this previously, `<MaxWidthText>` or something like that. Maybe `<LongText>` or `<Copy>` is better?

**Comment by jonborchardt** [comment]
Totally. It just got missed.
Will add.

**Comment by jonborchardt** [comment]
i added a component to varnish 2, added docs, and am using it on the template. (building on prod now)
