### ISSUE TITLE
skiff button tweaks

### ISSUE THREAD

**Issue by samstuesser** [allenai/varnish-mui#85]
Input / text field / dropdown theming and interaction look good!

**Button:** I don't hate the big button. It is a departure and may be intense if there are several on one page, but I like it when it's standalone like this. What do you think? I'm conflicted because it is really great by itself, but many instances of full-span buttons (mobile aside) may be intense. 

**Button Text:** letter-spacing should be 0.019, but I am ok with not rounding. it's quite literally an infinitesimal difference

**Comment by jonborchardt** [comment]
im good either way
i made the button match the original template
and i updated letter spacing

(template building now)
