### ISSUE TITLE
consider making "align-center" align the footer with the header logo on the left

### ISSUE THREAD

**Issue by samstuesser** [allenai/varnish-mui#86]
Just saw your note re: Skiff offering both centered and left-justified layouts.

This is just for the left-justified footer!

<img width="1271" alt="Screen Shot 2023-03-23 at 10 58 22 AM" src="https://user-images.githubusercontent.com/84743347/227302956-2cf8b6ee-3d40-4c05-b282-0d9f9862eb27.png">

**Footer:** I think this could be universally left-justified with the content grid, but I think it's a nice-to-have and not mandatory

**Comment by jonborchardt** [comment]
im going to leave this to match existing template for now.
but, we can make such changes if you want them made.
it is centered in most demos in the wild, so tal and let me know if you would prefer to prevent users from doing centered footers
