### ISSUE TITLE
Create documentation pointing to 3rd party libs

### ISSUE THREAD

**Issue by jonborchardt** [allenai/varnish-mui#96]
like
Yup
use-http
dayjs
formik
nivo

similar to: https://varnish.apps.allenai.org/components/thirdparty_libraries

**Comment by arnavic** [comment]
@jonborchardt - so for this, sounds like i should: 
1) copy over existing values from the Varnish 3rd party libraries page (maybe minus the AntD references, instead swapping in material UI ?)
2) add the ones you've mentioned in this issue that are not currently in the 3rd party libraries list such as Nivo, Day.JS, etc.?

**Comment by arnavic** [comment]
> @jonborchardt - so for this, sounds like i should:
> 
> 1. copy over existing values from the Varnish 3rd party libraries page (maybe minus the AntD references, instead swapping in material UI ?)
> 2. add the ones you've mentioned in this issue that are not currently in the 3rd party libraries list such as Nivo, Day.JS, etc.?

want to confirm that you don't want me adding only the ones you've called out in this issue, and that i should preserve the varnish1 recommended libraries as well

**Comment by jonborchardt** [comment]
No, just the one's n this ticket. The old varnish list can be ignored...
But you can use it as a template.
